from print_error import print_error


def test_print_error():
    print_error("Computer may explode at any moment.")


if __name__ == "__main__":
    test_print_error()
    print("print_error_test.py has been run.")